### PR TITLE
Updated harshit-paneri.md

### PR DESCRIPTION
**Pull request by sahil19solanki**
changed name

### CODE REVIEW

**Review by harshit-paneri — COMMENTED** [review]
Wrong File update, please add new file

**Comment by sahil19solanki** [comment]
added SAHILSolanki .md file

**Comment by sahil19solanki** [comment]
now if it is correct merge this

**Review by harshit-paneri — CHANGES_REQUESTED** [review]
image
Don't change other files (harshit-paneri.md).

**Pull request closed without merging**
