### PR TITLE
diiksha-agarwal.md

### PR DESCRIPTION
**Pull request by Diiksha-agarwal**
this is a practise thingy

### CODE REVIEW

**Comment by priyanshuarora595** [comment]
Wrong path. You had to add the file in contributors-list folder, not in the main directory

**Comment by Diiksha-agarwal** [comment]
On it

**Comment by Diiksha-agarwal** [comment]
A question tho if I end up making a mistake in a pull request can I like
cancel it later or something ?

**Comment by priyanshuarora595** [comment]
Yes you can.
This is called reverting a pull request.
Here is the documentation, you can read more about this.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request

**Comment by Diiksha-agarwal** [comment]
Thanks, I'll check it out. 🙃

**Pull request closed without merging**
